language: node_js
node_js:
  - stable


cache:
  directories:
    - "node_modules"


services:
  - postgresql



before_install:
  - npm install

before_script:
  - psql -c 'create database testcickodes;' -U postgres

script:
  - npm run coverage

after_success:
  - npm run coveralls

deploy:
  provider: heroku
  api_key: a6c6ab8d-7b79-40bb-84de-9b9565c7dd48
  app:
      develop: todo-app-io
